# This is a basic workflow to help you get started with Actions

name: CommunityToDevel

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the devel branch
on:
  pull_request:
    branches: [ devel ]

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - uses: actions/checkout@v2

      - name: Add ssh_key
        working-directory: /home/runner
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir .ssh
          chmod 700 .ssh
          echo "${{ secrets.SSH_PRV_KEY }}" > .ssh/github_actions
          chmod 600 .ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add .ssh/github_actions

### Build out the server
      - name: Terraform init
        working-directory: .github/workflows
        run: terraform init

      - name: Terraform format
        working-directory: .github/workflows
        run: terraform fmt

      - name: terraform validate
        working-directory: .github/workflows
        run: terraform validate

      - name: terraform apply
        working-directory: .github/workflows
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -var-file "rocky8.tfvars" --auto-approve

## debug ansible host file
#      - name: find ansible host file
#       working-directory: /home/runner
#        run: find ./ -name hosts.yml; cat `find ./ -name hosts.yml`
#      
      - name: Find ssh key 
        working-directory: /home/runner/.ssh
        run: pwd; ls -la; cat github_actions

      - name: Show Ansible hostfile
        working-directory: .github/workflows
        run: cat hosts.yml

## Run the ansible playbook

      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: site.yml
          inventory: .github/workflows/hosts.yml
          galaxy_file: collections/requirements.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
