// ssh key outputs
output "key_private_pem" {
  value = tls_private_key.github_actions.private_key_pem
  sensitive = true
}

output "key_public_openssh" {
  value = tls_private_key.github_actions.public_key_openssh
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.github_actions.private_key_pem
  sensitive = true
}